#!/usr/bin/env sh
node_modules/.bin/prettier --write --print-width 100 --single-quote --trailing-comma es5 --no-bracket-spacing --jsx-bracket-same-line "$@"
node_modules/.bin/eslint_d --no-eslintrc -c ./node_modules/eslint-config-mesaic/fix.js --fix "$@"
