#!/usr/bin/env sh
RED='\033[0;31m'
NC='\033[0m' # No Color

shift
jsfiles="$@"

echo >&2 $RED

test_files() {
  for f in $jsfiles; do
    cat $f | \
    ./node_modules/.bin/prettier --arrow-parens always --print-width 100 --single-quote --trailing-comma all --no-bracket-spacing --jsx-bracket-same-line --stdin |\
    ./node_modules/.bin/eslint_d --stdin --fix-to-stdout --no-eslintrc -c ./node_modules/@mesaic/eslint-config-mesaic/fix.js 2> /dev/null | \
    diff $f - &>/dev/null
    if [ "$?" != "0" ]; then
      echo $f
    fi
  done
}

diffs=$(test_files)

exit_code=0

if [ ! -z "$diffs" ]; then
  exit_code=1
  echo >&2 "${RED}Javascript files must be valid with eslint and prettier. Please run \`npm run format-staged\`. Failed files:"
  for file in $diffs; do echo >&2 "- $file"; done
fi

echo >&2 "${NC}"

exit $exit_code
